# Generated by Django 3.1.3 on 2020-11-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='announcments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BSCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.CharField(max_length=200, null=True)),
                ('course_work', models.CharField(max_length=200, null=True)),
                ('sem', models.CharField(max_length=10, null=True)),
                ('subject_teacher', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='students_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=500)),
                ('batch_no', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('dob', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(default='123456777', max_length=300)),
                ('due_date', models.DateField(auto_now=True)),
                ('admission_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('tution_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('Fine', models.FloatField(default=0, max_length=20, null=True)),
                ('withholding_tax', models.FloatField(default=0, max_length=20, null=True)),
                ('total_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Name')),
            ],
        ),
    ]
