# Generated by Django 3.0.3 on 2020-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.CharField(max_length=200, null=True)),
                ('course_work', models.CharField(max_length=200, null=True)),
                ('current_gpa', models.CharField(max_length=200, null=True)),
                ('cgpa', models.CharField(max_length=200, null=True)),
                ('subject_teacher', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
