# Generated by Django 3.0.3 on 2020-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.CharField(max_length=200, null=True)),
                ('course_work', models.CharField(max_length=200, null=True)),
                ('sem', models.CharField(max_length=10, null=True)),
                ('subject_teacher', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student_data',
        ),
    ]
