# Generated by Django 3.0.3 on 2020-10-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201022_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
