# Generated by Django 3.0.3 on 2020-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_students_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
