# Generated by Django 3.0.3 on 2020-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_announcments'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
