# Generated by Django 3.1.3 on 2020-12-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '__first__'),
        ('hods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='t',
            new_name='HOD_Teachers',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='std',
        ),
        migrations.AddField(
            model_name='hod',
            name='Department',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
