# Generated by Django 3.1.3 on 2020-12-17 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '__first__'),
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='batch_no',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('sec_batch', models.CharField(blank=True, help_text='pk', max_length=25, null=True)),
                ('batch', models.CharField(max_length=256, null=True)),
                ('section', models.CharField(help_text='Section Name Etc A,B,C etc', max_length=10, null=True)),
                ('limit', models.SmallIntegerField(blank=True, default=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default='1')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')])),
                ('semester_year', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('batchess', models.ManyToManyField(to='department.batch_no')),
                ('teachers_available', models.ManyToManyField(blank=True, related_name='teachers_available', to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(default=None, max_length=100)),
                ('subject2', models.CharField(default=None, max_length=100)),
                ('subject3', models.CharField(default=None, max_length=100)),
                ('subject4', models.CharField(default=None, max_length=100)),
                ('subject5', models.CharField(blank=True, default=None, max_length=100)),
                ('subject6', models.CharField(blank=True, default=None, max_length=100)),
                ('subject7', models.CharField(blank=True, default=None, max_length=100)),
                ('semester_subjects', models.ForeignKey(blank=True, default=None, help_text='Semester', null=True, on_delete=django.db.models.deletion.CASCADE, to='department.semester')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(help_text='Name of Department of Campus', max_length=255, unique=True, verbose_name='Department Name')),
                ('batches', models.ManyToManyField(blank=True, to='department.batch_no')),
                ('department_hod', models.ForeignKey(blank=True, default=None, help_text='Current HOD of Department', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_students', models.ManyToManyField(blank=True, related_name='students_in_department', to='student.Student')),
                ('department_teachers', models.ManyToManyField(blank=True, related_name='teachers_in_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch_no',
            name='depts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='batch_no',
            name='std_br',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('state', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=256)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.semester')),
                ('student', models.ManyToManyField(blank=True, to='student.Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='batch_no',
            unique_together={('batch', 'section')},
        ),
    ]
